name: ndk
description: Nostr Development Kit - the most performant lib for all your nostr usecases
version: 0.2.1
homepage: https://github.com/relaystr/ndk

environment:
  sdk: ">=3.4.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  http: ^1.2.2
  bip340: ^0.3.0
  bech32: ^0.2.2
  hex: ^0.2.0
  web_socket_channel: ^3.0.1
  crypto: ^3.0.5
  collection: ^1.18.0
  convert: ^3.1.1
  pointycastle: ^3.9.1
  logger: ^2.4.0
  rxdart: ^0.28.0
  equatable: ^2.0.7
  web_socket_client: ^0.1.5
  elliptic: ^0.3.11
  cryptography: ^2.7.0
  meta: ^1.15.0

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  mockito: ^5.0.17
  test: any
