name: ndk
description: Nostr Development Kit - the most performant lib for all your nostr usecases
version: 0.7.1-dev.2
homepage: https://github.com/relaystr/ndk
repository: https://github.com/relaystr/ndk

topics:
  - nostr

environment:
  sdk: ">=3.4.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  http: ^1.5.0
  bip340: ">=0.3.0 <0.4.0"
  bech32: ^0.2.2
  web_socket_channel: ^3.0.3
  crypto: ^3.0.6
  collection: ^1.19.1
  convert: ^3.1.2
  pointycastle: ">=3.0.0 <5.0.0"
  rxdart: ^0.28.0
  equatable: ^2.0.7
  web_socket_client: ^0.2.1
  elliptic: ^0.3.12
  cryptography: ^2.7.0
  meta: ">=1.10.0 <2.0.0"
  xxh3: ^1.2.0

dev_dependencies:
  build_runner: ^2.10.0
  build_version: ^2.1.3
  flutter_lints: ^6.0.0
  mockito: ^5.5.1
  test: any
  # shelf used for blossom mock server
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  ndk_cache_manager_test_suite:
    path: ../ndk_cache_manager_test_suite

