name: ndk_rust_verifier
description: Nostr Development Kit - the most performant lib for all your nostr usecases
version: 0.5.0-dev.11
homepage: https://github.com/relaystr/ndk

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.11.1
  rust_lib_ndk: ^0.1.7+1
  ndk: ^0.7.1-dev.11

#dependency_overrides:
#  rust_lib_ndk:
#    path: rust_builder
#  ndk:
#    path: ../ndk

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.0
  integration_test:
    sdk: flutter
