name: ndk_amber
description: Nostr Development Kit - the most performant lib for all your nostr usecases
version: 0.3.3-dev.16
homepage: https://github.com/relaystr/ndk

environment:
  sdk: ">=3.2.1 <4.0.0"
  flutter: ">=1.20.0"

platforms:
  android:

dependencies:
  flutter:
    sdk: flutter
  amberflutter: ^0.0.9
  hex: ^0.2.0
  plugin_platform_interface: ^2.1.8
  ndk: ^0.6.0-dev.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  mockito: ^5.4.6
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: relaystr.ndk
        pluginClass: DartNdkPlugin
