name: ndk_amber
description: Nostr Development Kit - the most performant lib for all your nostr usecases
version: 0.2.0
homepage: https://github.com/relaystr/ndk

environment:
  sdk: ">=3.2.1 <4.0.0"

platforms:
  android:

dependencies:
  flutter:
    sdk: flutter
  amberflutter: ^0.0.9
  hex: ^0.2.0
  plugin_platform_interface: ^2.1.8
  ndk: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.11
  mockito: ^5.0.17
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: relaystr.ndk
        pluginClass: DartNdkPlugin
