name: sembast_cache_manager
description: A Sembast-based cache manager for the NDK (Nostr Development Kit) library, providing persistent storage for Nostr protocol data.
version: 1.0.5-dev.14
homepage: https://github.com/relaystr/ndk
repository: https://github.com/relaystr/ndk

topics:
  - nostr

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  ndk: ^0.6.0-dev.11
  path: ^1.9.1
  sembast: ^3.8.5+1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
