name: ndk_objectbox
description: Nostr Development Kit - the most performant lib for all your nostr usecases
version: 0.2.7-dev.18
homepage: https://github.com/relaystr/ndk

environment:
  sdk: ">=3.4.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  objectbox: ^5.0.0
  objectbox_flutter_libs: ^5.0.0
  ndk: ^0.6.0-dev.13
  flat_buffers: ^23.5.26
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.5.0
  crypto: ^3.0.6

dev_dependencies:
  build_runner: ^2.5.4
  mockito: ^5.4.6
  objectbox_generator: ^5.0.0
  test: any
