name: ndk_objectbox
description: Nostr Development Kit - the most performant lib for all your nostr usecases
version: 0.2.8-dev.20
homepage: https://github.com/relaystr/ndk

environment:
  sdk: ">=3.4.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  objectbox: ^5.2.0 
  objectbox_flutter_libs: ^5.2.0
  ndk: ^0.7.1-dev.19
  flat_buffers: ^25.9.23
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.6.0
  crypto: ^3.0.7

dev_dependencies:
  build_runner: ^2.11.1 
  mockito: ^5.6.3
  objectbox_generator: ^5.2.0
  test: any
  ndk_cache_manager_test_suite:
    path: ../ndk_cache_manager_test_suite
  flutter_test:
    sdk: flutter

dependency_overrides:
  ndk:
    path: ../ndk
