name: ndk_isar
description: Nostr Development Kit - the most performant lib for all your nostr usecases
version: 0.2.3-dev.12
homepage: https://github.com/relaystr/ndk

environment:
  sdk: ">=3.4.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  isar: ^4.0.0-dev.14
  ndk: ^0.6.0-dev.9

dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  test: any
