name: ur
description: A Dart implementation of Uniform Resources (UR) encoding and decoding.
version: 0.1.0
homepage: https://github.com/bukata-sa/dart-bc-ur

environment:
  sdk: '>3.0.0'

dependencies:
  cbor: ^6.3.7
  ndk: ^0.7.1-dev.3

dev_dependencies:
  test: ^1.16.0
  lints: ^4.0.0

dependency_overrides: 
  ndk:
    path: ../ndk
