[package]
name = "rust_lib_ndk"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]


[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[dependencies]
flutter_rust_bridge = "=2.11.1"
hex = "0.4.3"
secp256k1 = { version = "0.31.1", features = ["global-context"] }
sha2 = "0.10.8"
serde_json = "1.0.128"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.16", features = ["js"] } # in later versions its wasm_js (feature name changed)

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = "0.2.16"
