[package]
name = "rust_lib_ndk"
version = "0.1.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.11.1"
hex = "0.4.3"
#secp256k1 = "0.29.1"
k256 = "0.13.4"  # Pure Rust implementation
sha2 = "0.10.8"
serde_json = "1.0.128"
bip39 = "2.1.0"  # Pure Rust BIP39 implementation
bip32 = "0.5.2"  # Pure Rust BIP32 implementation
rand_core = "0.6"  # For random number generation

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.16", features = ["js"] } # in later versions its wasm_js (feature name changed)

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
getrandom = "0.2.16"
