[package]
name = "rust_lib_ndk"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
hex = "0.4.3"
secp256k1 = "0.29.1"
sha2 = "0.10.8"
serde_json = "1.0.128"
