name: ndk_cache_manager_test_suite
description: Shared test suite for CacheManager implementations in the NDK (Nostr Development Kit) ecosystem.
publish_to: none
version: 1.0.1-dev.12
homepage: https://github.com/relaystr/ndk
repository: https://github.com/relaystr/ndk


environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  ndk: ^0.7.1-dev.18
  test: ^1.24.0

dev_dependencies:
  lints: ^5.0.0
