name: nip07_event_signer
description: Nostr nip07 signer for ndk
version: 1.0.6-dev.14
repository: https://github.com/relaystr/ndk

topics:
  - nostr

environment:
  sdk: ^3.8.1

dependencies:
  ndk: ^0.7.1-dev.14
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
