name: nip07_event_signer
description: Nostr nip07 signer for ndk
version: 1.0.4-dev.12
repository: https://github.com/relaystr/ndk

topics:
  - nostr

environment:
  sdk: ^3.8.1

dependencies:
  ndk: ^0.6.0-dev.9

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
